---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "spring-app-service"
  labels:
    app: "spring-app"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "spring-app"
  type: "LoadBalancer"
  # type: "NodePort"